default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  timeout: 5000
  user: <%= ENV['RAILS_DB_USER'] %>
  password: <%= ENV['RAILS_DB_PASSWORD'] %>
  host: <%= ENV['RAILS_DB_HOST'] %>
  port: <%= ENV['RAILS_DB_PORT'] %>

development:
  <<: *default
  database: dmd-development

test:
  <<: *default
  database: dmd-test

production:
  <<: *default
  database: dmd
