default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000
  username: <%= ENV['RAILS_DB_USER'] %>
  password: <%= ENV['RAILS_DB_PASSWORD'] %>
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: dmd-development

test:
  <<: *default
  database: dmd-test

production:
  <<: *default
  database: dmd
